# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainForm.ui'
#
# Created: Mon Sep 23 13:38:47 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1200, 600)
        MainWindow.setStyleSheet("QMainWindow {font-size : 400px; color : blue; background-image: url('plaza.jpg'); background-repeat:no-repeat;}")
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1200, 600))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Polish, QtCore.QLocale.Poland))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(1200, 600))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("TeXGyreCursor"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.centralwidget.setFont(font)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 15, 1081, 491))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.TableView = QtGui.QTableView(self.layoutWidget)
        self.TableView.setAutoFillBackground(True)
        self.TableView.setSortingEnabled(True)
        self.TableView.setObjectName(_fromUtf8("TableView"))
        self.TableView.horizontalHeader().setCascadingSectionResizes(True)
        self.TableView.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.TableView, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.ValueText = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("TeXGyreCursor"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.ValueText.setFont(font)
        self.ValueText.setAlignment(QtCore.Qt.AlignCenter)
        self.ValueText.setObjectName(_fromUtf8("ValueText"))
        self.verticalLayout.addWidget(self.ValueText)
        self.ValueBox = QtGui.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ValueBox.setFont(font)
        self.ValueBox.setMinimum(50)
        self.ValueBox.setMaximum(1000000)
        self.ValueBox.setSingleStep(50)
        self.ValueBox.setObjectName(_fromUtf8("ValueBox"))
        self.verticalLayout.addWidget(self.ValueBox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.MonthNumberText = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("TeXGyreCursor"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.MonthNumberText.setFont(font)
        self.MonthNumberText.setAlignment(QtCore.Qt.AlignCenter)
        self.MonthNumberText.setObjectName(_fromUtf8("MonthNumberText"))
        self.verticalLayout_2.addWidget(self.MonthNumberText)
        self.MonthNumberBox = QtGui.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("TeXGyreBonum"))
        font.setPointSize(12)
        font.setItalic(True)
        self.MonthNumberBox.setFont(font)
        self.MonthNumberBox.setMinimum(1)
        self.MonthNumberBox.setMaximum(48)
        self.MonthNumberBox.setObjectName(_fromUtf8("MonthNumberBox"))
        self.verticalLayout_2.addWidget(self.MonthNumberBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.GainText = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("TeXGyreCursor"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.GainText.setFont(font)
        self.GainText.setAlignment(QtCore.Qt.AlignCenter)
        self.GainText.setObjectName(_fromUtf8("GainText"))
        self.verticalLayout_3.addWidget(self.GainText)
        self.GainBox = QtGui.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("TeXGyreBonum"))
        font.setPointSize(12)
        font.setItalic(True)
        self.GainBox.setFont(font)
        self.GainBox.setMinimum(1)
        self.GainBox.setMaximum(48)
        self.GainBox.setObjectName(_fromUtf8("GainBox"))
        self.verticalLayout_3.addWidget(self.GainBox)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.RiskText = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("TeXGyreCursor"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.RiskText.setFont(font)
        self.RiskText.setAlignment(QtCore.Qt.AlignCenter)
        self.RiskText.setObjectName(_fromUtf8("RiskText"))
        self.verticalLayout_4.addWidget(self.RiskText)
        self.RiskBox = QtGui.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("TeXGyreBonum"))
        font.setPointSize(12)
        font.setItalic(True)
        self.RiskBox.setFont(font)
        self.RiskBox.setMinimum(1)
        self.RiskBox.setMaximum(48)
        self.RiskBox.setObjectName(_fromUtf8("RiskBox"))
        self.verticalLayout_4.addWidget(self.RiskBox)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.KeyText = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("TeXGyreCursor"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.KeyText.setFont(font)
        self.KeyText.setAlignment(QtCore.Qt.AlignCenter)
        self.KeyText.setObjectName(_fromUtf8("KeyText"))
        self.verticalLayout_6.addWidget(self.KeyText)
        self.KeyBox = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("TeXGyreBonum"))
        font.setPointSize(12)
        font.setItalic(True)
        self.KeyBox.setFont(font)
        self.KeyBox.setObjectName(_fromUtf8("KeyBox"))
        self.verticalLayout_6.addWidget(self.KeyBox)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem)
        self.SearchButton = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("TeXGyreCursor"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.SearchButton.setFont(font)
        self.SearchButton.setObjectName(_fromUtf8("SearchButton"))
        self.verticalLayout_5.addWidget(self.SearchButton)
        spacerItem1 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuPlik = QtGui.QMenu(self.menubar)
        self.menuPlik.setObjectName(_fromUtf8("menuPlik"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAktualizuj_Baze_Danych = QtGui.QAction(MainWindow)
        self.actionAktualizuj_Baze_Danych.setObjectName(_fromUtf8("actionAktualizuj_Baze_Danych"))
        self.actionZako_cz = QtGui.QAction(MainWindow)
        self.actionZako_cz.setObjectName(_fromUtf8("actionZako_cz"))
        self.actionO_Autorach = QtGui.QAction(MainWindow)
        self.actionO_Autorach.setObjectName(_fromUtf8("actionO_Autorach"))
        self.actionPomoc = QtGui.QAction(MainWindow)
        self.actionPomoc.setObjectName(_fromUtf8("actionPomoc"))
        self.menuPlik.addAction(self.actionAktualizuj_Baze_Danych)
        self.menuPlik.addSeparator()
        self.menuPlik.addAction(self.actionZako_cz)
        self.menuHelp.addAction(self.actionO_Autorach)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionPomoc)
        self.menubar.addAction(self.menuPlik.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Kokos.pl", None, QtGui.QApplication.UnicodeUTF8))
        self.ValueText.setText(QtGui.QApplication.translate("MainWindow", "Ile chcesz zainwestować?", None, QtGui.QApplication.UnicodeUTF8))
        self.MonthNumberText.setText(QtGui.QApplication.translate("MainWindow", "Max. liczba miesięcy?", None, QtGui.QApplication.UnicodeUTF8))
        self.GainText.setText(QtGui.QApplication.translate("MainWindow", "Zysk", None, QtGui.QApplication.UnicodeUTF8))
        self.RiskText.setText(QtGui.QApplication.translate("MainWindow", "Ryzyko", None, QtGui.QApplication.UnicodeUTF8))
        self.KeyText.setText(QtGui.QApplication.translate("MainWindow", "Twój klucz WebAPI", None, QtGui.QApplication.UnicodeUTF8))
        self.SearchButton.setText(QtGui.QApplication.translate("MainWindow", "Szukaj", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPlik.setTitle(QtGui.QApplication.translate("MainWindow", "Plik", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Pomoc", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAktualizuj_Baze_Danych.setText(QtGui.QApplication.translate("MainWindow", "Aktualizuj Baze Danych", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZako_cz.setText(QtGui.QApplication.translate("MainWindow", "Zakończ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionO_Autorach.setText(QtGui.QApplication.translate("MainWindow", "O Autorach", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPomoc.setText(QtGui.QApplication.translate("MainWindow", "O programie", None, QtGui.QApplication.UnicodeUTF8))

